import Foundation


// This file demonstrates how to use Swift Concurrency with Task groups to run multiple asynchronous child tasks, collect their results, and coordinate completion.

// Flush prints immediately to ensure output appears in real-time without buffering delays.
setbuf(stdout, nil)


//Function version of the previous code allowing for reuse
// Task allows async context to run, but async functions can be written above the entry of the context, basically im relearning how functions work


/**
 Demonstrates Swift Concurrency by executing multiple asynchronous tasks in parallel.
 
 This function showcases several Swift Concurrency features:
 - Creating asynchronous tasks with `Task`
 - Using task groups with `withTaskGroup`
 - Running multiple child tasks concurrently
 - Awaiting and collecting results from concurrent tasks
 
 The function performs these operations:
 1. Creates a root task to establish an asynchronous context
 2. Sets up a task group that spawns 5 child tasks
 3. Each child task sleeps for 1 second, simulating async work
 4. Collects and processes results as each child task completes
 5. Stops the main runloop after all async work is complete
 
 Note: The function uses `CFRunLoopRun()` to keep the main thread alive while
 the asynchronous work executes, which is necessary for Swift Concurrency to
 function correctly in command-line applications.
 
 - Important: This function will block the calling thread until all tasks complete.
 */
func runAsync(){
    print("Starting…")
    Task { //Enter the async context
        print("[root] async Task started")

        // Create a task group to run multiple child tasks concurrently and collect their results.
        await withTaskGroup(of: Int.self) { group in
            print("[root] creating child tasks")
            // Schedule five child tasks that each sleep for 1 second and then return their index.
            for i in 1...5 {
                group.addTask {
                    print("  [child \(i)] scheduled")
                    try? await Task.sleep(nanoseconds: 1_000_000_000)
                    print("  [child \(i)] returning")
                    return i
                }
            }

            print("[root] awaiting child results…")
            // Await each child task's result as they complete.
            for await idx in group {
                print("[root] received result from task \(idx)")
            }
            print("[root] all child results received")
        }

        // After all child tasks complete, stop the main runloop to allow the program to exit.
        print("[root] stopping runloop")
        CFRunLoopStop(CFRunLoopGetMain())
    }

    // Keep the main thread's runloop alive so Swift Concurrency can schedule tasks and run the async code.
    CFRunLoopRun()

    // Final message indicating all tasks have completed successfully.
    print("All tasks completed ✅")
}

/// Executes a specified number of tasks synchronously on a serial dispatch queue.
///
/// This function creates a serial dispatch queue and runs a series of tasks on it
/// synchronously. Each task sleeps for a specified duration, generates a random integer
/// between 1 and 200, and adds it to an array. The function prints status messages
/// during execution to track progress.
///
/// - Parameters:
///   - taskCount: The number of tasks to execute. Default value is 5.
///   - secondsPerTask: The number of seconds each task should sleep. Default value is 1.
///
/// - Returns: An array of random integers (between 1 and 200) generated by each task.
/// ```
/// let priorities = [3, 1, 5, 2, 4]
/// runPriority(taskCount: 3, secondsPerTask: 2, numList: priorities)
/// ```
func runPriority(taskCount: Int=5, secondsPerTask: UInt32=1, numList: [Int]) {
    let queue = DispatchQueue(label: "com.example.priority")
    var numsList = numList
    let group = DispatchGroup()

    /*
    queue.sync {
        print("[async priority] starting tasks with priority")
        for i in 1...taskCount {
            let maxValue = numsList.max()!
            let index = numsList.firstIndex(of: maxValue)!
            let ei = numList.firstIndex(of: numsList[index])!
            print("[priority task \(ei + 1)] starting; priority level: \(maxValue)")
            sleep(secondsPerTask)
            print("[priority task \(ei + 1)] completed")
            numsList.remove(at: index)
        }

        print("[priority] all priority tasks completed ✅" )
    }
    */

    print("[priority] starting tasks with priority")
    for i in 1...taskCount {
        group.enter()
        queue.async(group: group) {
            let maxValue = numsList.max()!
            let index = numsList.firstIndex(of: maxValue)!
            let ei = numList.firstIndex(of: numsList[index])!
            print("[priority task \(ei + 1)] starting; priority level: \(maxValue)")
            sleep(secondsPerTask)
            print("[priority task \(ei + 1)] completed")
            numsList.remove(at: index)
            group.leave()
        }

        
    }
    group.wait()
    print("[priority] all priority tasks completed ✅" )
}

runAsync()
print()
print()
var list = runSync()
print()
print()
runPriority(numList: list)
